// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowsersyncParams = { targetDir: string, proxyUrl: string, extensions: Array<string>, ghostMode: GhostMode, };

export type GhostMode = { clicks: boolean, scroll: boolean, forms: boolean, };
